spring:
  servlet:
    multipart:
      max-file-size: 50MB

# Environment variables configured on "Run/debug Configurations"
awsRegion: ${AWS_REGION}
awsAccessKey: ${AWS_ACCESS_KEY}
awsSecretAccessKey: ${AWS_SECRET_ACCESS_KEY}